name: tempahkenderaan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#
version: 1.0.0+5

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  geocoding: ^4.0.0
  flutter_map: ^6.1.0
  universal_platform: ^1.0.0+1
  flutter_map_cancellable_tile_provider: ^1.0.0
  pdf: ^3.10.0
  printing: ^5.11.0
  google_fonts: ^6.0.0
  animations: ^2.0.7
  share_plus: ^7.2.1 
  intl: ^0.18.1
  crypto: ^3.0.3
  connectivity_plus: ^5.0.2 
  fl_chart: ^0.64.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/home.png"
  adaptive_icon_foreground: "assets/home.png"
  adaptive_icon_background: "#FFFFFF"


    

  
  


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/booking.png
     - assets/home.png
     - assets/home1.png
     - assets/car.png
     - assets/emobil.png
     - assets/carm.png
     - assets/fonts/NotoSans-Regular.ttf

    

  

 
fonts:
     - family: Schyler
       fonts:
         - asset:  assets/fonts/NotoSans-Regular.ttf
         - asset:  assets/fonts/NotoSans-italic.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700